// 衛福部精華版資料庫 (Curated Taiwan Food Database)
// 擴充版：包含近 250 筆台灣常見食物、小吃、與超商連鎖食品
const foodDatabase = {
    categories: [
        { id: 'bento', name: '街邊便當與小吃', icon: 'fluent-emoji-flat:bento-box', color: '#FBBF24' },
        { id: 'breakfast', name: '台灣靈魂早餐', icon: 'fluent-emoji-flat:cooking', color: '#ff6b6b' },
        { id: 'store', name: '超商快充站', icon: 'fluent-emoji-flat:convenience-store', color: '#38BDF8' },
        { id: 'raw', name: '原型生鮮食材', icon: 'fluent-emoji-flat:leafy-green', color: '#1dd1a1' },
        { id: 'supp', name: '戰術補給與自訂', icon: 'fluent-emoji-flat:high-voltage', color: '#A78BFA' },
        { id: 'cheat', name: '快樂舒壓餐', icon: 'fluent-emoji-flat:bubble-tea', color: '#ff9ff3' }
    ],
    foods: [
        // ================= 街邊便當與小吃 (日常混合餐) =================
        { id: 's17', categoryId: 'bento', name: '水餃 (10顆)', cals: 500, macros: { p: 20, c: 45, f: 25 }, icon: 'fluent-emoji-flat:dumpling' },
        { id: 's18', categoryId: 'bento', name: '鍋貼 (10顆)', cals: 650, macros: { p: 20, c: 60, f: 35 }, icon: 'fluent-emoji-flat:dumpling' },
        { id: 's19', categoryId: 'bento', name: '小籠包 (8顆)', cals: 550, macros: { p: 22, c: 50, f: 28 }, icon: 'fluent-emoji-flat:dumpling' },
        { id: 's20', categoryId: 'bento', name: '陽春麵 (湯/1碗)', cals: 320, macros: { p: 10, c: 60, f: 3 }, icon: 'fluent-emoji-flat:steaming-bowl' },
        { id: 's21', categoryId: 'bento', name: '乾麵/麻醬麵 (1碗)', cals: 450, macros: { p: 12, c: 60, f: 18 }, icon: 'fluent-emoji-flat:steaming-bowl' },
        { id: 's22', categoryId: 'bento', name: '義大利麵 (番茄/1份)', cals: 500, macros: { p: 15, c: 75, f: 15 }, icon: 'fluent-emoji-flat:spaghetti' },
        { id: 's23', categoryId: 'bento', name: '義大利麵 (白醬/1份)', cals: 700, macros: { p: 20, c: 70, f: 35 }, icon: 'fluent-emoji-flat:spaghetti' },
        { id: 's24', categoryId: 'bento', name: '義大利麵 (青醬/1份)', cals: 650, macros: { p: 18, c: 65, f: 30 }, icon: 'fluent-emoji-flat:spaghetti' },
        { id: 's25', categoryId: 'bento', name: '烏龍麵 (湯/1碗)', cals: 250, macros: { p: 8, c: 50, f: 2 }, icon: 'fluent-emoji-flat:steaming-bowl' },
        { id: 's26', categoryId: 'bento', name: '冬粉 (1把/煮熟)', cals: 140, macros: { p: 0, c: 35, f: 0 }, icon: 'fluent-emoji-flat:steaming-bowl' },
        { id: 's27', categoryId: 'bento', name: '米粉 (炒/1份)', cals: 450, macros: { p: 8, c: 60, f: 20 }, icon: 'fluent-emoji-flat:steaming-bowl' },
        { id: 's29', categoryId: 'bento', name: '肉粽 (1顆)', cals: 550, macros: { p: 15, c: 60, f: 25 }, icon: 'fluent-emoji-flat:rice-ball' },
        { id: 'm4', categoryId: 'bento', name: '三杯雞 (1份)', cals: 450, macros: { p: 30, c: 10, f: 30 }, icon: 'fluent-emoji-flat:poultry-leg' },
        { id: 'm12', categoryId: 'bento', name: '豬腳 (滷/1塊)', cals: 350, macros: { p: 20, c: 5, f: 25 }, icon: 'fluent-emoji-flat:meat-on-bone' },
        { id: 'v29', categoryId: 'bento', name: '麻婆豆腐 (1份)', cals: 250, macros: { p: 12, c: 15, f: 15 }, icon: 'fluent-emoji-flat:pot-of-food' },
        { id: 'v30', categoryId: 'bento', name: '三杯杏鮑菇 (1份)', cals: 200, macros: { p: 5, c: 15, f: 12 }, icon: 'fluent-emoji-flat:mushroom' },
        { id: 'e1', categoryId: 'bento', name: '排骨便當 (炸/1個)', cals: 900, macros: { p: 35, c: 100, f: 40 }, icon: 'fluent-emoji-flat:bento-box' },
        { id: 'e2', categoryId: 'bento', name: '排骨便當 (滷/1個)', cals: 750, macros: { p: 35, c: 95, f: 25 }, icon: 'fluent-emoji-flat:bento-box' },
        { id: 'e3', categoryId: 'bento', name: '雞腿便當 (炸/1個)', cals: 850, macros: { p: 38, c: 95, f: 35 }, icon: 'fluent-emoji-flat:bento-box' },
        { id: 'e4', categoryId: 'bento', name: '雞腿便當 (烤/1個)', cals: 780, macros: { p: 45, c: 90, f: 26 }, icon: 'fluent-emoji-flat:bento-box' },
        { id: 'e5', categoryId: 'bento', name: '控肉便當 (1個)', cals: 900, macros: { p: 30, c: 90, f: 47 }, icon: 'fluent-emoji-flat:bento-box' },
        { id: 'e6', categoryId: 'bento', name: '燒肉便當 (1個)', cals: 720, macros: { p: 32, c: 90, f: 25 }, icon: 'fluent-emoji-flat:bento-box' },
        { id: 'e7', categoryId: 'bento', name: '鯖魚便當 (1個)', cals: 750, macros: { p: 38, c: 90, f: 27 }, icon: 'fluent-emoji-flat:bento-box' },
        { id: 'e8', categoryId: 'bento', name: '鮭魚便當 (1個)', cals: 780, macros: { p: 35, c: 90, f: 31 }, icon: 'fluent-emoji-flat:bento-box' },
        { id: 'e9', categoryId: 'bento', name: '三寶飯便當 (1個)', cals: 950, macros: { p: 40, c: 95, f: 45 }, icon: 'fluent-emoji-flat:bento-box' },
        { id: 'e10', categoryId: 'bento', name: '素食便當 (1個)', cals: 650, macros: { p: 20, c: 95, f: 20 }, icon: 'fluent-emoji-flat:bento-box' },
        { id: 'e11', categoryId: 'bento', name: '滷肉飯 (小碗)', cals: 400, macros: { p: 8, c: 50, f: 18 }, icon: 'fluent-emoji-flat:curry-rice' },
        { id: 'e12', categoryId: 'bento', name: '滷肉飯 (大碗)', cals: 600, macros: { p: 15, c: 75, f: 26 }, icon: 'fluent-emoji-flat:bowl-with-spoon' },
        { id: 'e13', categoryId: 'bento', name: '火雞肉飯 (1碗)', cals: 350, macros: { p: 12, c: 50, f: 10 }, icon: 'fluent-emoji-flat:cooked-rice' },
        { id: 'e14', categoryId: 'bento', name: '肉絲炒飯 (1份)', cals: 700, macros: { p: 20, c: 90, f: 28 }, icon: 'fluent-emoji-flat:curry-rice' },
        { id: 'e15', categoryId: 'bento', name: '蝦仁炒飯 (1份)', cals: 680, macros: { p: 22, c: 90, f: 25 }, icon: 'fluent-emoji-flat:curry-rice' },
        { id: 'e16', categoryId: 'bento', name: '牛肉麵 (紅燒/1碗)', cals: 750, macros: { p: 35, c: 80, f: 30 }, icon: 'fluent-emoji-flat:steaming-bowl' },
        { id: 'e17', categoryId: 'bento', name: '牛肉麵 (清燉/1碗)', cals: 600, macros: { p: 35, c: 75, f: 15 }, icon: 'fluent-emoji-flat:steaming-bowl' },
        { id: 'e18', categoryId: 'bento', name: '什錦炒麵 (1份)', cals: 650, macros: { p: 20, c: 75, f: 30 }, icon: 'fluent-emoji-flat:steaming-bowl' },
        { id: 'e19', categoryId: 'bento', name: '大腸麵線 (1碗)', cals: 400, macros: { p: 10, c: 55, f: 15 }, icon: 'fluent-emoji-flat:bowl-with-spoon' },
        { id: 'e20', categoryId: 'bento', name: '蚵仔麵線 (大碗)', cals: 450, macros: { p: 15, c: 60, f: 16 }, icon: 'fluent-emoji-flat:bowl-with-spoon' },
        { id: 'e21', categoryId: 'bento', name: '肉羹麵 (1碗)', cals: 550, macros: { p: 15, c: 70, f: 20 }, icon: 'fluent-emoji-flat:steaming-bowl' },
        { id: 'e22', categoryId: 'bento', name: '大腸包小腸 (1份)', cals: 580, macros: { p: 15, c: 45, f: 35 }, icon: 'fluent-emoji-flat:hot-dog' },
        { id: 'e30', categoryId: 'bento', name: '肉圓 (炸/1顆)', cals: 350, macros: { p: 8, c: 40, f: 17 }, icon: 'fluent-emoji-flat:dumpling' },
        { id: 'e31', categoryId: 'bento', name: '肉圓 (清蒸/1顆)', cals: 200, macros: { p: 8, c: 35, f: 3 }, icon: 'fluent-emoji-flat:dumpling' },
        { id: 'e32', categoryId: 'bento', name: '火鍋 (大眾牛/清湯)', cals: 700, macros: { p: 40, c: 60, f: 30 }, icon: 'fluent-emoji-flat:pot-of-food' },
        { id: 'e33', categoryId: 'bento', name: '火鍋 (麻辣鍋/含湯)', cals: 1200, macros: { p: 45, c: 60, f: 80 }, icon: 'fluent-emoji-flat:pot-of-food' },
        { id: 'e34', categoryId: 'bento', name: '涼麵 (芝麻醬/1份)', cals: 550, macros: { p: 15, c: 60, f: 25 }, icon: 'fluent-emoji-flat:spaghetti' },
        { id: 'e35', categoryId: 'bento', name: '皮蛋豆腐 (1份)', cals: 180, macros: { p: 16, c: 5, f: 10 }, icon: 'fluent-emoji-flat:egg' },
        { id: 'e36', categoryId: 'bento', name: '蚵仔煎 (1份)', cals: 450, macros: { p: 15, c: 50, f: 20 }, icon: 'fluent-emoji-flat:oyster' },
        { id: 'e37', categoryId: 'bento', name: '潤餅 (1捲)', cals: 300, macros: { p: 10, c: 45, f: 8 }, icon: 'fluent-emoji-flat:burrito' },
        { id: 'st10', categoryId: 'bento', name: 'Subway 烤雞肉堡 (6吋)', cals: 320, macros: { p: 23, c: 45, f: 5 }, icon: 'fluent-emoji-flat:sandwich' },
        { id: 'st11', categoryId: 'bento', name: 'Subway 鮪魚堡 (6吋)', cals: 450, macros: { p: 20, c: 45, f: 22 }, icon: 'fluent-emoji-flat:sandwich' },

        // ================= 台灣靈魂早餐 (早晨專區) =================
        { id: 's12', categoryId: 'breakfast', name: '白吐司 (1片/50g)', cals: 140, macros: { p: 4, c: 26, f: 2 }, icon: 'fluent-emoji-flat:bread' },
        { id: 's13', categoryId: 'breakfast', name: '全麥吐司 (1片/50g)', cals: 130, macros: { p: 5, c: 24, f: 2 }, icon: 'fluent-emoji-flat:bread' },
        { id: 's14', categoryId: 'breakfast', name: '原味貝果 (1個/100g)', cals: 260, macros: { p: 10, c: 50, f: 1 }, icon: 'fluent-emoji-flat:bagel' },
        { id: 's15', categoryId: 'breakfast', name: '菠蘿麵包 (1個)', cals: 400, macros: { p: 7, c: 55, f: 16 }, icon: 'fluent-emoji-flat:croissant' },
        { id: 's16', categoryId: 'breakfast', name: '白饅頭 (1顆)', cals: 280, macros: { p: 8, c: 60, f: 1 }, icon: 'fluent-emoji-flat:dumpling' },
        { id: 's28', categoryId: 'breakfast', name: '蘿蔔糕 (2片)', cals: 220, macros: { p: 4, c: 30, f: 10 }, icon: 'fluent-emoji-flat:fortune-cookie' },
        { id: 's30', categoryId: 'breakfast', name: '一片麵包 (約50g)', cals: 140, macros: { p: 4, c: 26, f: 2 }, icon: 'fluent-emoji-flat:bread' },
        { id: 's31', categoryId: 'breakfast', name: '饅頭 (1顆)', cals: 280, macros: { p: 8, c: 60, f: 1 }, icon: 'fluent-emoji-flat:dumpling' },
        { id: 'e38', categoryId: 'breakfast', name: '蔥油餅/蔥抓餅 (1份)', cals: 400, macros: { p: 8, c: 45, f: 20 }, icon: 'fluent-emoji-flat:flatbread' },
        { id: 'e39', categoryId: 'breakfast', name: '水煎包 (鮮肉/1顆)', cals: 250, macros: { p: 10, c: 25, f: 12 }, icon: 'fluent-emoji-flat:dumpling' },
        { id: 'e40', categoryId: 'breakfast', name: '胡椒餅 (1顆)', cals: 350, macros: { p: 12, c: 45, f: 13 }, icon: 'fluent-emoji-flat:bagel' },
        { id: 'e41', categoryId: 'breakfast', name: '原味蛋餅 (1份)', cals: 250, macros: { p: 8, c: 30, f: 10 }, icon: 'fluent-emoji-flat:burrito' },
        { id: 'e42', categoryId: 'breakfast', name: '鮪魚蛋餅 (1份)', cals: 350, macros: { p: 15, c: 35, f: 15 }, icon: 'fluent-emoji-flat:burrito' },
        { id: 'e43', categoryId: 'breakfast', name: '培根蛋餅 (1份)', cals: 380, macros: { p: 12, c: 35, f: 20 }, icon: 'fluent-emoji-flat:burrito' },
        { id: 'e44', categoryId: 'breakfast', name: '肉包 (1顆)', cals: 280, macros: { p: 8, c: 35, f: 12 }, icon: 'fluent-emoji-flat:dumpling' },
        { id: 'e45', categoryId: 'breakfast', name: '菜包 (1顆)', cals: 220, macros: { p: 6, c: 35, f: 5 }, icon: 'fluent-emoji-flat:dumpling' },
        { id: 'd2', categoryId: 'breakfast', name: '拿鐵咖啡 (無糖/中杯)', cals: 150, macros: { p: 8, c: 12, f: 8 }, icon: 'fluent-emoji-flat:hot-beverage' },
        { id: 'd3', categoryId: 'breakfast', name: '美式咖啡 (無糖)', cals: 15, macros: { p: 0, c: 3, f: 0 }, icon: 'fluent-emoji-flat:hot-beverage' },

        // ================= 超商快充站 (微波與即食) =================
        { id: 'st12', categoryId: 'store', name: '超商 御飯糰 (鮪魚)', cals: 210, macros: { p: 5, c: 40, f: 3 }, icon: 'fluent-emoji-flat:rice-ball' },
        { id: 'st13', categoryId: 'store', name: '超商 御飯糰 (肉鬆)', cals: 220, macros: { p: 5, c: 42, f: 4 }, icon: 'fluent-emoji-flat:rice-ball' },
        { id: 'st14', categoryId: 'store', name: '超商 烤雞三明治', cals: 280, macros: { p: 12, c: 35, f: 10 }, icon: 'fluent-emoji-flat:sandwich' },
        { id: 'st15', categoryId: 'store', name: '超商 微波義大利麵', cals: 550, macros: { p: 20, c: 70, f: 20 }, icon: 'fluent-emoji-flat:spaghetti' },
        { id: 'st16', categoryId: 'store', name: '超商 即食雞胸肉 (100g)', cals: 110, macros: { p: 24, c: 1, f: 1 }, icon: 'fluent-emoji-flat:chicken' },
        { id: 'st17', categoryId: 'store', name: '超商 烤地瓜 (100g)', cals: 125, macros: { p: 1, c: 29, f: 0 }, icon: 'fluent-emoji-flat:roasted-sweet-potato' },
        { id: 'st18', categoryId: 'store', name: '超商 生菜沙拉 (和風醬)', cals: 100, macros: { p: 3, c: 15, f: 2 }, icon: 'fluent-emoji-flat:green-salad' },
        { id: 'st19', categoryId: 'store', name: '超商 茶葉蛋 (1顆)', cals: 75, macros: { p: 7, c: 1, f: 5 }, icon: 'fluent-emoji-flat:egg' },
        { id: 'v24', categoryId: 'store', name: '茶葉蛋/滷蛋 (1顆)', cals: 75, macros: { p: 7, c: 1, f: 5 }, icon: 'fluent-emoji-flat:egg' },
        { id: 'st20', categoryId: 'store', name: '義美 無糖黑豆奶 (400ml)', cals: 145, macros: { p: 14, c: 6, f: 7 }, icon: 'fluent-emoji-flat:glass-of-milk' },
        { id: 'st21', categoryId: 'store', name: '光泉 無糖鮮豆漿 (400ml)', cals: 140, macros: { p: 14, c: 6, f: 7 }, icon: 'fluent-emoji-flat:glass-of-milk' },
        { id: 'st22', categoryId: 'store', name: '統一 陽光無糖豆漿', cals: 155, macros: { p: 16, c: 6, f: 8 }, icon: 'fluent-emoji-flat:glass-of-milk' },
        { id: 'st23', categoryId: 'store', name: '林鳳營 全脂鮮奶 (230ml)', cals: 150, macros: { p: 7, c: 11, f: 9 }, icon: 'fluent-emoji-flat:glass-of-milk' },
        { id: 'd1', categoryId: 'store', name: '無糖綠茶/烏龍/紅茶', cals: 0, macros: { p: 0, c: 0, f: 0 }, icon: 'fluent-emoji-flat:teacup-without-handle' },
        { id: 'd4', categoryId: 'store', name: '全脂鮮奶 (250ml)', cals: 160, macros: { p: 8, c: 12, f: 9 }, icon: 'fluent-emoji-flat:glass-of-milk' },
        { id: 'd5', categoryId: 'store', name: '燕麥奶 (250ml)', cals: 130, macros: { p: 3, c: 15, f: 5 }, icon: 'fluent-emoji-flat:glass-of-milk' },

        // ================= 原型生鮮食材 (自煮備餐區) =================
        { id: 's1', categoryId: 'raw', name: '白飯 (1平碗/160g)', cals: 280, macros: { p: 5, c: 60, f: 1 }, icon: 'fluent-emoji-flat:cooked-rice' },
        { id: 's2', categoryId: 'raw', name: '糙米飯 (1碗/160g)', cals: 260, macros: { p: 6, c: 54, f: 2 }, icon: 'fluent-emoji-flat:cooked-rice' },
        { id: 's3', categoryId: 'raw', name: '五穀米 (1碗/160g)', cals: 250, macros: { p: 7, c: 52, f: 2 }, icon: 'fluent-emoji-flat:cooked-rice' },
        { id: 's4', categoryId: 'raw', name: '紫米飯 (1碗/160g)', cals: 265, macros: { p: 6, c: 56, f: 1.5 }, icon: 'fluent-emoji-flat:cooked-rice' },
        { id: 's5', categoryId: 'raw', name: '地瓜 (1條/150g)', cals: 195, macros: { p: 2, c: 45, f: 0 }, icon: 'fluent-emoji-flat:roasted-sweet-potato' },
        { id: 's6', categoryId: 'raw', name: '馬鈴薯 (1顆/150g)', cals: 120, macros: { p: 3, c: 27, f: 0 }, icon: 'fluent-emoji-flat:potato' },
        { id: 's7', categoryId: 'raw', name: '南瓜 (1碗/100g)', cals: 70, macros: { p: 2, c: 17, f: 0 }, icon: 'fluent-emoji-flat:jack-o-lantern' },
        { id: 's8', categoryId: 'raw', name: '芋頭 (100g)', cals: 130, macros: { p: 2.5, c: 30, f: 0 }, icon: 'fluent-emoji-flat:roasted-sweet-potato' },
        { id: 's9', categoryId: 'raw', name: '山藥 (100g)', cals: 75, macros: { p: 2, c: 17, f: 0 }, icon: 'fluent-emoji-flat:potato' },
        { id: 's10', categoryId: 'raw', name: '玉米 (1根/150g)', cals: 150, macros: { p: 5, c: 33, f: 2 }, icon: 'fluent-emoji-flat:ear-of-corn' },
        { id: 's11', categoryId: 'raw', name: '燕麥片 (乾重50g)', cals: 190, macros: { p: 7, c: 33, f: 4 }, icon: 'fluent-emoji-flat:bowl-with-spoon' },
        { id: 'm1', categoryId: 'raw', name: '水煮雞胸肉 (100g)', cals: 110, macros: { p: 24, c: 0, f: 1 }, icon: 'fluent-emoji-flat:chicken' },
        { id: 'm2', categoryId: 'raw', name: '烤/煎雞腿排 (100g)', cals: 210, macros: { p: 18, c: 0, f: 15 }, icon: 'fluent-emoji-flat:poultry-leg' },
        { id: 'm3', categoryId: 'raw', name: '雞里肌肉 (100g)', cals: 105, macros: { p: 23, c: 0, f: 1 }, icon: 'fluent-emoji-flat:chicken' },
        { id: 'm5', categoryId: 'raw', name: '滷牛腱 (100g)', cals: 140, macros: { p: 28, c: 0, f: 3 }, icon: 'fluent-emoji-flat:cut-of-meat' },
        { id: 'm6', categoryId: 'raw', name: '牛排 (沙朗/100g)', cals: 250, macros: { p: 20, c: 0, f: 18 }, icon: 'fluent-emoji-flat:cut-of-meat' },
        { id: 'm7', categoryId: 'raw', name: '牛排 (菲力/100g)', cals: 135, macros: { p: 21, c: 0, f: 5 }, icon: 'fluent-emoji-flat:cut-of-meat' },
        { id: 'm8', categoryId: 'raw', name: '牛五花肉片 (100g)', cals: 430, macros: { p: 15, c: 0, f: 40 }, icon: 'fluent-emoji-flat:bacon' },
        { id: 'm9', categoryId: 'raw', name: '豬里肌肉 (瘦/100g)', cals: 150, macros: { p: 22, c: 0, f: 6 }, icon: 'fluent-emoji-flat:cut-of-meat' },
        { id: 'm10', categoryId: 'raw', name: '豬梅花肉片 (100g)', cals: 280, macros: { p: 18, c: 0, f: 22 }, icon: 'fluent-emoji-flat:bacon' },
        { id: 'm11', categoryId: 'raw', name: '豬五花肉 (100g)', cals: 360, macros: { p: 14, c: 0, f: 33 }, icon: 'fluent-emoji-flat:bacon' },
        { id: 'm13', categoryId: 'raw', name: '鮭魚片 (100g)', cals: 220, macros: { p: 20, c: 0, f: 15 }, icon: 'fluent-emoji-flat:fish' },
        { id: 'm14', categoryId: 'raw', name: '鯛魚片 (100g)', cals: 100, macros: { p: 20, c: 0, f: 2 }, icon: 'fluent-emoji-flat:fish' },
        { id: 'm15', categoryId: 'raw', name: '秋刀魚 (1尾/150g)', cals: 450, macros: { p: 27, c: 0, f: 38 }, icon: 'fluent-emoji-flat:fish' },
        { id: 'm16', categoryId: 'raw', name: '虱目魚肚 (100g)', cals: 250, macros: { p: 18, c: 0, f: 20 }, icon: 'fluent-emoji-flat:fish' },
        { id: 'm17', categoryId: 'raw', name: '鱈魚 (煎/100g)', cals: 200, macros: { p: 15, c: 5, f: 14 }, icon: 'fluent-emoji-flat:fish' },
        { id: 'm18', categoryId: 'raw', name: '蝦仁/白蝦 (100g)', cals: 90, macros: { p: 20, c: 0, f: 1 }, icon: 'fluent-emoji-flat:shrimp' },
        { id: 'm19', categoryId: 'raw', name: '蛤蜊/鮮蚵 (100g)', cals: 70, macros: { p: 10, c: 4, f: 2 }, icon: 'fluent-emoji-flat:oyster' },
        { id: 'm20', categoryId: 'raw', name: '透抽/魷魚 (100g)', cals: 80, macros: { p: 16, c: 2, f: 1 }, icon: 'fluent-emoji-flat:squid' },
        { id: 'm21', categoryId: 'raw', name: '干貝 (100g)', cals: 90, macros: { p: 18, c: 3, f: 1 }, icon: 'fluent-emoji-flat:spiral-shell' },
        { id: 'm22', categoryId: 'raw', name: '羊肉片 (100g)', cals: 200, macros: { p: 18, c: 0, f: 14 }, icon: 'fluent-emoji-flat:cut-of-meat' },
        { id: 'v1', categoryId: 'raw', name: '水煮蛋 (1顆)', cals: 75, macros: { p: 6.5, c: 0.5, f: 5 }, icon: 'fluent-emoji-flat:egg' },
        { id: 'v2', categoryId: 'raw', name: '荷包蛋/煎蛋 (1顆)', cals: 110, macros: { p: 6.5, c: 0.5, f: 9 }, icon: 'fluent-emoji-flat:cooking' },
        { id: 'v3', categoryId: 'raw', name: '炒蛋/滑蛋 (1份)', cals: 150, macros: { p: 7, c: 2, f: 12 }, icon: 'fluent-emoji-flat:cooking' },
        { id: 'v25', categoryId: 'raw', name: '蔥花蛋 (1份)', cals: 150, macros: { p: 10, c: 2, f: 11 }, icon: 'fluent-emoji-flat:cooking' },
        { id: 'v4', categoryId: 'raw', name: '無糖豆漿 (400ml)', cals: 140, macros: { p: 14, c: 6, f: 7 }, icon: 'fluent-emoji-flat:glass-of-milk' },
        { id: 'v5', categoryId: 'raw', name: '傳統豆腐 (半塊/150g)', cals: 130, macros: { p: 13, c: 3, f: 8 }, icon: 'fluent-emoji-flat:white-large-square' },
        { id: 'v6', categoryId: 'raw', name: '嫩豆腐 (1盒/300g)', cals: 150, macros: { p: 15, c: 6, f: 8 }, icon: 'fluent-emoji-flat:white-large-square' },
        { id: 'v7', categoryId: 'raw', name: '百頁豆腐 (半條/100g)', cals: 215, macros: { p: 13, c: 5, f: 17 }, icon: 'fluent-emoji-flat:white-large-square' },
        { id: 'v8', categoryId: 'raw', name: '豆干 (3片/100g)', cals: 160, macros: { p: 19, c: 6, f: 7 }, icon: 'fluent-emoji-flat:oden' },
        { id: 'v9', categoryId: 'raw', name: '毛豆 (仁/100g)', cals: 120, macros: { p: 11, c: 10, f: 5 }, icon: 'fluent-emoji-flat:pea-pod' },
        { id: 'v10', categoryId: 'raw', name: '高麗菜 (燙1盤)', cals: 40, macros: { p: 2, c: 8, f: 0 }, icon: 'fluent-emoji-flat:leafy-green' },
        { id: 'v11', categoryId: 'raw', name: '炒青菜 (油炒1盤)', cals: 120, macros: { p: 2, c: 8, f: 10 }, icon: 'fluent-emoji-flat:leafy-green' },
        { id: 'v12', categoryId: 'raw', name: '花椰菜 (燙/100g)', cals: 25, macros: { p: 2, c: 5, f: 0 }, icon: 'fluent-emoji-flat:broccoli' },
        { id: 'v13', categoryId: 'raw', name: '綜合生菜沙拉 (不加醬)', cals: 30, macros: { p: 1, c: 6, f: 0 }, icon: 'fluent-emoji-flat:green-salad' },
        { id: 'v14', categoryId: 'raw', name: '凱薩沙拉 (含醬)', cals: 250, macros: { p: 8, c: 15, f: 18 }, icon: 'fluent-emoji-flat:green-salad' },
        { id: 'v15', categoryId: 'raw', name: '綜合菇類 (100g)', cals: 35, macros: { p: 3, c: 5, f: 0 }, icon: 'fluent-emoji-flat:mushroom' },
        { id: 'v16', categoryId: 'raw', name: '番茄 (大顆/100g)', cals: 18, macros: { p: 1, c: 4, f: 0 }, icon: 'fluent-emoji-flat:tomato' },
        { id: 'v17', categoryId: 'raw', name: '洋蔥 (100g)', cals: 40, macros: { p: 1, c: 9, f: 0 }, icon: 'fluent-emoji-flat:onion' },
        { id: 'v18', categoryId: 'raw', name: '胡蘿蔔 (100g)', cals: 40, macros: { p: 1, c: 9, f: 0 }, icon: 'fluent-emoji-flat:carrot' },
        { id: 'v19', categoryId: 'raw', name: '小黃瓜 (100g)', cals: 15, macros: { p: 1, c: 3, f: 0 }, icon: 'fluent-emoji-flat:cucumber' },
        { id: 'v20', categoryId: 'raw', name: '茄子 (100g)', cals: 25, macros: { p: 1, c: 6, f: 0 }, icon: 'fluent-emoji-flat:eggplant' },
        { id: 'v21', categoryId: 'raw', name: '橄欖油/沙拉油 (1茶匙/5g)', cals: 45, macros: { p: 0, c: 0, f: 5 }, icon: 'fluent-emoji-flat:olive' },
        { id: 'v22', categoryId: 'raw', name: '綜合堅果 (1把/30g)', cals: 180, macros: { p: 6, c: 6, f: 15 }, icon: 'fluent-emoji-flat:peanuts' },
        { id: 'v23', categoryId: 'raw', name: '花生醬 (1湯匙)', cals: 100, macros: { p: 4, c: 3, f: 8 }, icon: 'fluent-emoji-flat:peanuts' },
        { id: 'v26', categoryId: 'raw', name: '燙青菜 (拌肉燥/1份)', cals: 100, macros: { p: 2, c: 5, f: 8 }, icon: 'fluent-emoji-flat:leafy-green' },
        { id: 'v27', categoryId: 'raw', name: '炒空心菜 (1份/100g)', cals: 70, macros: { p: 2, c: 4, f: 5 }, icon: 'fluent-emoji-flat:leafy-green' },
        { id: 'v28', categoryId: 'raw', name: '番茄炒蛋 (1份)', cals: 180, macros: { p: 8, c: 10, f: 12 }, icon: 'fluent-emoji-flat:tomato' },
        { id: 'f1', categoryId: 'raw', name: '香蕉 (1根)', cals: 110, macros: { p: 1, c: 28, f: 0 }, icon: 'fluent-emoji-flat:banana' },
        { id: 'f2', categoryId: 'raw', name: '蘋果 (1顆)', cals: 95, macros: { p: 0.5, c: 25, f: 0 }, icon: 'fluent-emoji-flat:red-apple' },
        { id: 'f3', categoryId: 'raw', name: '奇異果 (1顆)', cals: 45, macros: { p: 1, c: 11, f: 0 }, icon: 'fluent-emoji-flat:kiwi-fruit' },
        { id: 'f4', categoryId: 'raw', name: '橘子/柳丁 (1顆)', cals: 60, macros: { p: 1, c: 15, f: 0 }, icon: 'fluent-emoji-flat:tangerine' },
        { id: 'f5', categoryId: 'raw', name: '芭樂 (1顆/200g)', cals: 75, macros: { p: 1, c: 17, f: 0 }, icon: 'fluent-emoji-flat:green-apple' },
        { id: 'f6', categoryId: 'raw', name: '西瓜 (1碗切塊)', cals: 60, macros: { p: 1, c: 15, f: 0 }, icon: 'fluent-emoji-flat:watermelon' },
        { id: 'f7', categoryId: 'raw', name: '鳳梨 (1碗切塊)', cals: 65, macros: { p: 0.5, c: 16, f: 0 }, icon: 'fluent-emoji-flat:pineapple' },
        { id: 'f8', categoryId: 'raw', name: '木瓜 (1碗切塊)', cals: 55, macros: { p: 1, c: 14, f: 0 }, icon: 'fluent-emoji-flat:melon' },
        { id: 'f9', categoryId: 'raw', name: '葡萄 (10顆)', cals: 60, macros: { p: 0.5, c: 15, f: 0 }, icon: 'fluent-emoji-flat:grapes' },
        { id: 'f10', categoryId: 'raw', name: '草莓 (10顆)', cals: 40, macros: { p: 1, c: 9, f: 0 }, icon: 'fluent-emoji-flat:strawberry' },

        // ================= 戰術補給與自訂特調 (你的專屬護城河) =================
        { id: 'd10', categoryId: 'supp', name: '高蛋白飲 (1匙+水)', cals: 120, macros: { p: 25, c: 2, f: 1 }, icon: 'fluent-emoji-flat:cup-with-straw' },
        { id: 'st24', categoryId: 'supp', name: 'ON 乳清蛋白 (1匙)', cals: 120, macros: { p: 24, c: 3, f: 1 }, icon: 'fluent-emoji-flat:cup-with-straw' },
        { id: 'st25', categoryId: 'supp', name: 'Myprotein 乳清 (1匙)', cals: 100, macros: { p: 21, c: 1, f: 2 }, icon: 'fluent-emoji-flat:cup-with-straw' },
        { id: 'st26', categoryId: 'supp', name: '戰神 MARS 乳清 (1包)', cals: 140, macros: { p: 26, c: 4, f: 2 }, icon: 'fluent-emoji-flat:cup-with-straw' },
        { id: 'st27', categoryId: 'supp', name: '果果堅果 乳清 (1匙)', cals: 120, macros: { p: 22, c: 4, f: 2 }, icon: 'fluent-emoji-flat:cup-with-straw' },

        // ================= 快樂舒壓餐 (欺騙餐) =================
        { id: 'e23', categoryId: 'cheat', name: '炸雞排 (1塊)', cals: 650, macros: { p: 30, c: 40, f: 40 }, icon: 'fluent-emoji-flat:poultry-leg' },
        { id: 'e24', categoryId: 'cheat', name: '鹹酥雞 (1份)', cals: 550, macros: { p: 25, c: 30, f: 35 }, icon: 'fluent-emoji-flat:poultry-leg' },
        { id: 'e25', categoryId: 'cheat', name: '甜不辣 (炸/1份)', cals: 300, macros: { p: 8, c: 35, f: 14 }, icon: 'fluent-emoji-flat:oden' },
        { id: 'e26', categoryId: 'cheat', name: '地瓜球 (1小份)', cals: 300, macros: { p: 2, c: 40, f: 15 }, icon: 'fluent-emoji-flat:dango' },
        { id: 'e27', categoryId: 'cheat', name: '臭豆腐 (炸/1份)', cals: 500, macros: { p: 15, c: 35, f: 33 }, icon: 'fluent-emoji-flat:falafel' },
        { id: 'e28', categoryId: 'cheat', name: '豬血糕 (1支)', cals: 200, macros: { p: 6, c: 35, f: 4 }, icon: 'fluent-emoji-flat:oden' },
        { id: 'e29', categoryId: 'cheat', name: '章魚燒 (6顆)', cals: 300, macros: { p: 8, c: 35, f: 14 }, icon: 'fluent-emoji-flat:dango' },
        { id: 'st1', categoryId: 'cheat', name: '麥當勞 大麥克', cals: 540, macros: { p: 26, c: 45, f: 28 }, icon: 'fluent-emoji-flat:hamburger' },
        { id: 'st2', categoryId: 'cheat', name: '麥當勞 麥香雞', cals: 380, macros: { p: 14, c: 38, f: 19 }, icon: 'fluent-emoji-flat:hamburger' },
        { id: 'st3', categoryId: 'cheat', name: '麥當勞 麥香魚', cals: 330, macros: { p: 15, c: 35, f: 14 }, icon: 'fluent-emoji-flat:hamburger' },
        { id: 'st4', categoryId: 'cheat', name: '麥當勞 麥克雞塊 (6塊)', cals: 270, macros: { p: 14, c: 17, f: 16 }, icon: 'fluent-emoji-flat:poultry-leg' },
        { id: 'st5', categoryId: 'cheat', name: '麥當勞 中薯', cals: 330, macros: { p: 4, c: 42, f: 16 }, icon: 'fluent-emoji-flat:french-fries' },
        { id: 'st6', categoryId: 'cheat', name: '肯德基 咔啦脆雞/雞腿堡', cals: 480, macros: { p: 20, c: 48, f: 23 }, icon: 'fluent-emoji-flat:hamburger' },
        { id: 'st7', categoryId: 'cheat', name: '肯德基 原味蛋撻 (1個)', cals: 180, macros: { p: 3, c: 18, f: 10 }, icon: 'fluent-emoji-flat:pie' },
        { id: 'st8', categoryId: 'cheat', name: '摩斯 海洋珍珠堡', cals: 420, macros: { p: 12, c: 65, f: 12 }, icon: 'fluent-emoji-flat:hamburger' },
        { id: 'st9', categoryId: 'cheat', name: '摩斯 蜜汁烤雞堡', cals: 360, macros: { p: 16, c: 43, f: 14 }, icon: 'fluent-emoji-flat:hamburger' },
        { id: 'd6', categoryId: 'cheat', name: '珍珠奶茶 (全糖/大杯)', cals: 700, macros: { p: 5, c: 120, f: 20 }, icon: 'fluent-emoji-flat:bubble-tea' },
        { id: 'd7', categoryId: 'cheat', name: '珍珠奶茶 (微糖/大杯)', cals: 500, macros: { p: 5, c: 80, f: 18 }, icon: 'fluent-emoji-flat:bubble-tea' },
        { id: 'd8', categoryId: 'cheat', name: '鮮奶茶 (微糖/大杯)', cals: 250, macros: { p: 8, c: 35, f: 8 }, icon: 'fluent-emoji-flat:bubble-tea' },
        { id: 'd9', categoryId: 'cheat', name: '手搖果茶 (半糖/大杯)', cals: 300, macros: { p: 0, c: 75, f: 0 }, icon: 'fluent-emoji-flat:tropical-drink' },
        { id: 'd11', categoryId: 'cheat', name: '可口可樂 (330ml)', cals: 140, macros: { p: 0, c: 35, f: 0 }, icon: 'fluent-emoji-flat:cup-with-straw' },
        { id: 'd12', categoryId: 'cheat', name: '運動飲料 (600ml)', cals: 160, macros: { p: 0, c: 40, f: 0 }, icon: 'fluent-emoji-flat:droplet' }
    ]
};
