// 衛福部精華版資料庫 (Curated Taiwan Food Database)
// 涵蓋日常 99% 常見飲食，包含原型食物與台灣小吃外食
const foodDatabase = {
    categories: [
        { id: 'staple', name: '常吃主食', icon: 'fa-bowl-rice' },
        { id: 'meat', name: '肉類與海鮮', icon: 'fa-drumstick-bite' },
        { id: 'veg', name: '蔬菜與蛋豆', icon: 'fa-carrot' },
        { id: 'snack', name: '外食與小吃', icon: 'fa-burger' },
        { id: 'drink', name: '飲料與水果', icon: 'fa-apple-whole' }
    ],
    foods: [
        // ================= 常吃主食 (Staple) =================
        { id: 's1', categoryId: 'staple', name: '白飯 (1平碗/160g)', cals: 280, macros: { p: 5, c: 60, f: 1 }, icon: '🍚' },
        { id: 's2', categoryId: 'staple', name: '糙米飯 (1碗/160g)', cals: 260, macros: { p: 6, c: 54, f: 2 }, icon: '🍚' },
        { id: 's3', categoryId: 'staple', name: '五穀米 (1碗/160g)', cals: 250, macros: { p: 7, c: 52, f: 2 }, icon: '🍚' },
        { id: 's4', categoryId: 'staple', name: '地瓜 (1條/150g)', cals: 195, macros: { p: 2, c: 45, f: 0 }, icon: '🍠' },
        { id: 's5', categoryId: 'staple', name: '馬鈴薯 (1顆/150g)', cals: 120, macros: { p: 3, c: 27, f: 0 }, icon: '🥔' },
        { id: 's6', categoryId: 'staple', name: '南瓜 (1碗/100g)', cals: 70, macros: { p: 2, c: 17, f: 0 }, icon: '🎃' },
        { id: 's7', categoryId: 'staple', name: '玉米 (1根/150g)', cals: 150, macros: { p: 5, c: 33, f: 2 }, icon: '🌽' },
        { id: 's8', categoryId: 'staple', name: '燕麥片 (乾重50g)', cals: 190, macros: { p: 7, c: 33, f: 4 }, icon: '🥣' },
        { id: 's9', categoryId: 'staple', name: '白吐司 (1片/50g)', cals: 140, macros: { p: 4, c: 26, f: 2 }, icon: '🍞' },
        { id: 's10', categoryId: 'staple', name: '全麥吐司 (1片/50g)', cals: 130, macros: { p: 5, c: 24, f: 2 }, icon: '🍞' },
        { id: 's11', categoryId: 'staple', name: '原味貝果 (1個/100g)', cals: 260, macros: { p: 10, c: 50, f: 1 }, icon: '🥯' },
        { id: 's12', categoryId: 'staple', name: '菠蘿麵包 (1個)', cals: 400, macros: { p: 7, c: 55, f: 16 }, icon: '🥐' },
        { id: 's13', categoryId: 'staple', name: '白饅頭 (1顆)', cals: 280, macros: { p: 8, c: 60, f: 1 }, icon: '🥟' },
        { id: 's14', categoryId: 'staple', name: '水餃 (10顆)', cals: 500, macros: { p: 20, c: 45, f: 25 }, icon: '🥟' },
        { id: 's15', categoryId: 'staple', name: '鍋貼 (10顆)', cals: 650, macros: { p: 20, c: 60, f: 35 }, icon: '🥟' },
        { id: 's16', categoryId: 'staple', name: '陽春麵 (湯/1碗)', cals: 320, macros: { p: 10, c: 60, f: 3 }, icon: '🍜' },
        { id: 's17', categoryId: 'staple', name: '乾麵/麻醬麵 (1碗)', cals: 450, macros: { p: 12, c: 60, f: 18 }, icon: '🍜' },
        { id: 's18', categoryId: 'staple', name: '義大利麵 (番茄/1份)', cals: 500, macros: { p: 15, c: 75, f: 15 }, icon: '🍝' },
        { id: 's19', categoryId: 'staple', name: '義大利麵 (白醬/1份)', cals: 700, macros: { p: 20, c: 70, f: 35 }, icon: '🍝' },
        { id: 's20', categoryId: 'staple', name: '烏龍麵 (湯/1碗)', cals: 250, macros: { p: 8, c: 50, f: 2 }, icon: '🍜' },
        { id: 's21', categoryId: 'staple', name: '蘿蔔糕 (2片)', cals: 220, macros: { p: 4, c: 30, f: 10 }, icon: '🥠' },

        // ================= 肉類與海鮮 (Meat) =================
        { id: 'm1', categoryId: 'meat', name: '水煮雞胸肉 (100g)', cals: 110, macros: { p: 24, c: 0, f: 1 }, icon: '🐔' },
        { id: 'm2', categoryId: 'meat', name: '烤/煎雞腿排 (100g)', cals: 210, macros: { p: 18, c: 0, f: 15 }, icon: '🍗' },
        { id: 'm3', categoryId: 'meat', name: '滷牛腱 (100g)', cals: 140, macros: { p: 28, c: 0, f: 3 }, icon: '🥩' },
        { id: 'm4', categoryId: 'meat', name: '牛排 (沙朗/100g)', cals: 250, macros: { p: 20, c: 0, f: 18 }, icon: '🥩' },
        { id: 'm5', categoryId: 'meat', name: '牛五花肉片 (100g)', cals: 430, macros: { p: 15, c: 0, f: 40 }, icon: '🥓' },
        { id: 'm6', categoryId: 'meat', name: '豬里肌肉 (瘦/100g)', cals: 150, macros: { p: 22, c: 0, f: 6 }, icon: '🥩' },
        { id: 'm7', categoryId: 'meat', name: '豬梅花肉片 (100g)', cals: 280, macros: { p: 18, c: 0, f: 22 }, icon: '🥓' },
        { id: 'm8', categoryId: 'meat', name: '豬五花肉 (100g)', cals: 360, macros: { p: 14, c: 0, f: 33 }, icon: '🥓' },
        { id: 'm9', categoryId: 'meat', name: '鮭魚片 (100g)', cals: 220, macros: { p: 20, c: 0, f: 15 }, icon: '🐟' },
        { id: 'm10', categoryId: 'meat', name: '鯛魚片 (100g)', cals: 100, macros: { p: 20, c: 0, f: 2 }, icon: '🐟' },
        { id: 'm11', categoryId: 'meat', name: '秋刀魚 (1尾/150g)', cals: 450, macros: { p: 27, c: 0, f: 38 }, icon: '🐟' },
        { id: 'm12', categoryId: 'meat', name: '虱目魚 (100g)', cals: 200, macros: { p: 21, c: 0, f: 13 }, icon: '🐟' },
        { id: 'm13', categoryId: 'meat', name: '蝦仁/白蝦 (100g)', cals: 90, macros: { p: 20, c: 0, f: 1 }, icon: '🦐' },
        { id: 'm14', categoryId: 'meat', name: '蛤蜊/鮮蚵 (100g)', cals: 70, macros: { p: 10, c: 4, f: 2 }, icon: '🦪' },
        { id: 'm15', categoryId: 'meat', name: '透抽/魷魚 (100g)', cals: 80, macros: { p: 16, c: 2, f: 1 }, icon: '🦑' },

        // ================= 蔬菜與蛋豆 (Veg) =================
        { id: 'v1', categoryId: 'veg', name: '水煮蛋 (1顆)', cals: 75, macros: { p: 6.5, c: 0.5, f: 5 }, icon: '🥚' },
        { id: 'v2', categoryId: 'veg', name: '荷包蛋/煎蛋 (1顆)', cals: 110, macros: { p: 6.5, c: 0.5, f: 9 }, icon: '🍳' },
        { id: 'v3', categoryId: 'veg', name: '超商茶葉蛋 (1顆)', cals: 80, macros: { p: 7, c: 1, f: 5 }, icon: '🥚' },
        { id: 'v4', categoryId: 'veg', name: '無糖豆漿 (400ml)', cals: 140, macros: { p: 14, c: 6, f: 7 }, icon: '🥛' },
        { id: 'v5', categoryId: 'veg', name: '微糖豆漿 (400ml)', cals: 180, macros: { p: 14, c: 16, f: 7 }, icon: '🥛' },
        { id: 'v6', categoryId: 'veg', name: '傳統豆腐 (半塊/150g)', cals: 130, macros: { p: 13, c: 3, f: 8 }, icon: '🤍' },
        { id: 'v7', categoryId: 'veg', name: '嫩豆腐 (1盒/300g)', cals: 150, macros: { p: 15, c: 6, f: 8 }, icon: '🤍' },
        { id: 'v8', categoryId: 'veg', name: '豆干 (3片/100g)', cals: 160, macros: { p: 19, c: 6, f: 7 }, icon: '🤎' },
        { id: 'v9', categoryId: 'veg', name: '毛豆 (仁/100g)', cals: 120, macros: { p: 11, c: 10, f: 5 }, icon: '🫛' },
        { id: 'v10', categoryId: 'veg', name: '高麗菜/青江菜 (燙1盤)', cals: 40, macros: { p: 2, c: 8, f: 0 }, icon: '🥬' },
        { id: 'v11', categoryId: 'veg', name: '炒青菜 (油炒1盤)', cals: 120, macros: { p: 2, c: 8, f: 10 }, icon: '🥬' },
        { id: 'v12', categoryId: 'veg', name: '花椰菜 (100g)', cals: 25, macros: { p: 2, c: 5, f: 0 }, icon: '🥦' },
        { id: 'v13', categoryId: 'veg', name: '綜合生菜沙拉 (不加醬)', cals: 30, macros: { p: 1, c: 6, f: 0 }, icon: '🥗' },
        { id: 'v14', categoryId: 'veg', name: '綜合菇類 (100g)', cals: 35, macros: { p: 3, c: 5, f: 0 }, icon: '🍄' },
        { id: 'v15', categoryId: 'veg', name: '番茄 (大顆/100g)', cals: 18, macros: { p: 1, c: 4, f: 0 }, icon: '🍅' },

        // ================= 外食與小吃 (Snacks & Meals) =================
        { id: 'e1', categoryId: 'snack', name: '排骨便當 (炸/1個)', cals: 900, macros: { p: 35, c: 100, f: 40 }, icon: '🍱' },
        { id: 'e2', categoryId: 'snack', name: '排骨便當 (滷/1個)', cals: 750, macros: { p: 35, c: 95, f: 25 }, icon: '🍱' },
        { id: 'e3', categoryId: 'snack', name: '雞腿便當 (炸/1個)', cals: 850, macros: { p: 38, c: 95, f: 35 }, icon: '🍱' },
        { id: 'e4', categoryId: 'snack', name: '滷肉飯 (小碗)', cals: 400, macros: { p: 8, c: 50, f: 18 }, icon: '🍛' },
        { id: 'e5', categoryId: 'snack', name: '火雞肉飯 (小碗)', cals: 350, macros: { p: 12, c: 50, f: 10 }, icon: '🍚' },
        { id: 'e6', categoryId: 'snack', name: '牛肉麵 (紅燒/1碗)', cals: 750, macros: { p: 35, c: 80, f: 30 }, icon: '🍜' },
        { id: 'e7', categoryId: 'snack', name: '大腸麵線 (1碗)', cals: 400, macros: { p: 10, c: 55, f: 15 }, icon: '🥣' },
        { id: 'e8', categoryId: 'snack', name: '鹹酥雞 (1份)', cals: 550, macros: { p: 25, c: 30, f: 35 }, icon: '🍗' },
        { id: 'e9', categoryId: 'snack', name: '炸雞排 (1塊)', cals: 650, macros: { p: 30, c: 40, f: 40 }, icon: '🍗' },
        { id: 'e10', categoryId: 'snack', name: '大腸包小腸 (1份)', cals: 580, macros: { p: 15, c: 45, f: 35 }, icon: '🌭' },
        { id: 'e11', categoryId: 'snack', name: '臭豆腐 (炸/1份)', cals: 500, macros: { p: 15, c: 35, f: 33 }, icon: '🧆' },
        { id: 'e12', categoryId: 'snack', name: '章魚燒 (6顆)', cals: 300, macros: { p: 8, c: 35, f: 14 }, icon: '🍡' },
        { id: 'e13', categoryId: 'snack', name: '麥當勞 大麥克', cals: 540, macros: { p: 26, c: 45, f: 28 }, icon: '🍔' },
        { id: 'e14', categoryId: 'snack', name: '麥當勞 中薯', cals: 330, macros: { p: 4, c: 42, f: 16 }, icon: '🍟' },
        { id: 'e15', categoryId: 'snack', name: '火鍋 (大眾牛/清湯)', cals: 700, macros: { p: 40, c: 60, f: 30 }, icon: '🍲' },
        { id: 'e16', categoryId: 'snack', name: '鮪魚蛋餅 (1份)', cals: 350, macros: { p: 15, c: 35, f: 15 }, icon: '🌯' },
        { id: 'e17', categoryId: 'snack', name: '培根蛋餅 (1份)', cals: 380, macros: { p: 12, c: 35, f: 20 }, icon: '🌯' },
        { id: 'e18', categoryId: 'snack', name: '肉包/菜包 (1顆)', cals: 280, macros: { p: 8, c: 35, f: 12 }, icon: '🥟' },
        { id: 'e19', categoryId: 'snack', name: '超商御飯糰 (鮪魚/肉鬆)', cals: 210, macros: { p: 5, c: 40, f: 3 }, icon: '🍙' },
        { id: 'e20', categoryId: 'snack', name: '涼麵 (芝麻醬/1份)', cals: 550, macros: { p: 15, c: 60, f: 25 }, icon: '🍝' },

        // ================= 飲料與水果 (Drinks & Fruits) =================
        { id: 'd1', categoryId: 'drink', name: '無糖綠茶/烏龍/紅茶', cals: 0, macros: { p: 0, c: 0, f: 0 }, icon: '🍵' },
        { id: 'd2', categoryId: 'drink', name: '拿鐵咖啡 (無糖/中杯)', cals: 150, macros: { p: 8, c: 12, f: 8 }, icon: '☕' },
        { id: 'd3', categoryId: 'drink', name: '美式咖啡 (無糖)', cals: 15, macros: { p: 0, c: 3, f: 0 }, icon: '☕' },
        { id: 'd4', categoryId: 'drink', name: '全脂鮮奶 (250ml)', cals: 160, macros: { p: 8, c: 12, f: 9 }, icon: '🥛' },
        { id: 'd5', categoryId: 'drink', name: '燕麥奶 (250ml)', cals: 130, macros: { p: 3, c: 15, f: 5 }, icon: '🥛' },
        { id: 'd6', categoryId: 'drink', name: '珍珠奶茶 (全糖/中杯)', cals: 550, macros: { p: 4, c: 95, f: 15 }, icon: '🧋' },
        { id: 'd7', categoryId: 'drink', name: '珍珠奶茶 (微糖/中杯)', cals: 400, macros: { p: 4, c: 65, f: 12 }, icon: '🧋' },
        { id: 'd8', categoryId: 'drink', name: '手搖果茶 (半糖/中杯)', cals: 250, macros: { p: 0, c: 60, f: 0 }, icon: '🍹' },
        { id: 'd9', categoryId: 'drink', name: '高蛋白飲 (1匙+水)', cals: 120, macros: { p: 25, c: 2, f: 1 }, icon: '🥤' },
        { id: 'd10', categoryId: 'drink', name: '香蕉 (1根)', cals: 110, macros: { p: 1, c: 28, f: 0 }, icon: '🍌' },
        { id: 'd11', categoryId: 'drink', name: '蘋果 (1顆)', cals: 95, macros: { p: 0.5, c: 25, f: 0 }, icon: '🍎' },
        { id: 'd12', categoryId: 'drink', name: '奇異果 (1顆)', cals: 45, macros: { p: 1, c: 11, f: 0 }, icon: '🥝' },
        { id: 'd13', categoryId: 'drink', name: '橘子/柳丁 (1顆)', cals: 60, macros: { p: 1, c: 15, f: 0 }, icon: '🍊' },
        { id: 'd14', categoryId: 'drink', name: '芭樂 (1顆/200g)', cals: 75, macros: { p: 1, c: 17, f: 0 }, icon: '🍏' },
        { id: 'd15', categoryId: 'drink', name: '西瓜 (1碗切塊)', cals: 60, macros: { p: 1, c: 15, f: 0 }, icon: '🍉' },
        { id: 'd16', categoryId: 'drink', name: '鳳梨 (1碗切塊)', cals: 65, macros: { p: 0.5, c: 16, f: 0 }, icon: '🍍' }
    ]
};
